/**
 * Mock data for local preview without Supabase.
 * Replace with real Supabase data once .env.local is filled in.
 */

import { Category, Product } from '@/types'

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Heels & Stilettos', slug: 'heels-stilettos', description: 'Elevate every outfit with our curated collection of heels and stilettos.', image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop', sort_order: 1, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Boots & Ankle Boots', slug: 'boots-ankle-boots', description: 'From sleek ankle boots to statement knee-highs.', image_url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop', sort_order: 2, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Sneakers', slug: 'sneakers', description: 'Fashionable sneakers that blend comfort with street-chic style.', image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop', sort_order: 3, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-4', name: 'Dresses', slug: 'dresses', description: 'From daytime florals to evening glamour.', image_url: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop', sort_order: 4, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-5', name: 'Tops & Sets', slug: 'tops-sets', description: 'Effortlessly chic tops, blouses, and coordinated sets.', image_url: 'https://images.unsplash.com/photo-1485230405346-71acb9518d9c?w=600&auto=format&fit=crop', sort_order: 5, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
  { id: 'cat-6', name: 'Accessories', slug: 'accessories', description: 'Complete your look with our curated accessories.', image_url: 'https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=600&auto=format&fit=crop', sort_order: 6, is_active: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
]

const cat = (id: string) => mockCategories.find(c => c.id === id) ?? null

// Spread mock product timestamps across 12 days so New Arrivals sort works in preview
const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()

export const mockProducts: Product[] = [
  { id: 'p-1', category_id: 'cat-1', name: 'Velvet Gold-Strap Stiletto', description: 'Luxurious velvet finish with a delicate gold ankle strap. 10cm heel. Perfect for evening events.', price: 89.99, image_url: 'https://images.unsplash.com/photo-1518049362265-d5b2a6467637?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40','41'], is_featured: true, is_active: true, sort_order: 1, created_at: daysAgo(0), updated_at: daysAgo(0), category: cat('cat-1') },
  { id: 'p-2', category_id: 'cat-1', name: 'Crystal Clear Mule Heel', description: 'Transparent PVC mule with a sculpted block heel. The shoe that goes with everything.', price: 69.99, image_url: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40'], is_featured: false, is_active: true, sort_order: 2, created_at: daysAgo(1), updated_at: daysAgo(1), category: cat('cat-1') },
  { id: 'p-3', category_id: 'cat-2', name: 'Snake-Print Chelsea Boot', description: 'Faux snake-print leather Chelsea boot with elastic side panels. Chunky sole.', price: 119.99, image_url: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40','41'], is_featured: true, is_active: true, sort_order: 3, created_at: daysAgo(2), updated_at: daysAgo(2), category: cat('cat-2') },
  { id: 'p-4', category_id: 'cat-2', name: 'Over-the-Knee Suede Boot', description: 'Plush suede over-the-knee boot with a 5cm block heel. A wardrobe essential.', price: 149.99, image_url: 'https://images.unsplash.com/photo-1512374382149-233c42b6a83b?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40'], is_featured: false, is_active: true, sort_order: 4, created_at: daysAgo(3), updated_at: daysAgo(3), category: cat('cat-2') },
  { id: 'p-5', category_id: 'cat-3', name: 'Rhinestone Platform Sneaker', description: 'White leather platform sneaker embellished with rhinestone accents. 4cm platform.', price: 79.99, image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40','41'], is_featured: false, is_active: true, sort_order: 5, created_at: daysAgo(4), updated_at: daysAgo(4), category: cat('cat-3') },
  { id: 'p-6', category_id: 'cat-3', name: 'Iridescent Chunky Sneaker', description: 'Holographic iridescent finish on a chunky sole. Sporty meets glam.', price: 94.99, image_url: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?w=600&auto=format&fit=crop', additional_images: null, sizes: ['36','37','38','39','40'], is_featured: true, is_active: true, sort_order: 6, created_at: daysAgo(5), updated_at: daysAgo(5), category: cat('cat-3') },
  { id: 'p-7', category_id: 'cat-4', name: 'Satin Slip Midi Dress', description: 'Bias-cut satin slip dress in champagne gold. Adjustable spaghetti straps.', price: 109.99, image_url: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&auto=format&fit=crop', additional_images: null, sizes: ['XS','S','M','L','XL'], is_featured: true, is_active: true, sort_order: 7, created_at: daysAgo(6), updated_at: daysAgo(6), category: cat('cat-4') },
  { id: 'p-8', category_id: 'cat-4', name: 'Cutout Bodycon Maxi', description: 'Black stretch-jersey maxi dress with strategic side cutouts. Invisible zip.', price: 134.99, image_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&auto=format&fit=crop', additional_images: null, sizes: ['XS','S','M','L'], is_featured: false, is_active: true, sort_order: 8, created_at: daysAgo(7), updated_at: daysAgo(7), category: cat('cat-4') },
  { id: 'p-9', category_id: 'cat-5', name: 'Corset Bralette Top', description: 'Structured boned corset bralette in ivory lace. Busk front fastening.', price: 59.99, image_url: 'https://images.unsplash.com/photo-1485230405346-71acb9518d9c?w=600&auto=format&fit=crop', additional_images: null, sizes: ['XS','S','M','L','XL'], is_featured: false, is_active: true, sort_order: 9, created_at: daysAgo(8), updated_at: daysAgo(8), category: cat('cat-5') },
  { id: 'p-10', category_id: 'cat-5', name: 'Sequin Co-Ord Set', description: 'Two-piece co-ord set: cropped blazer and flared trousers in silver sequin.', price: 179.99, image_url: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=600&auto=format&fit=crop', additional_images: null, sizes: ['XS','S','M','L'], is_featured: true, is_active: true, sort_order: 10, created_at: daysAgo(9), updated_at: daysAgo(9), category: cat('cat-5') },
  { id: 'p-11', category_id: 'cat-6', name: 'Gold Chain Statement Bag', description: 'Mini croc-embossed bag with thick gold chain strap. Magnetic clasp closure.', price: 74.99, image_url: 'https://images.unsplash.com/photo-1492707892479-7bc8d5a4ee93?w=600&auto=format&fit=crop', additional_images: null, sizes: null, is_featured: false, is_active: true, sort_order: 11, created_at: daysAgo(10), updated_at: daysAgo(10), category: cat('cat-6') },
  { id: 'p-12', category_id: 'cat-6', name: 'Crystal Hair Claw Clip', description: 'Oversized acetate claw clip adorned with hand-set crystals. Holds thick hair.', price: 29.99, image_url: 'https://images.unsplash.com/photo-1524117074681-31bd4de22ad3?w=600&auto=format&fit=crop', additional_images: null, sizes: null, is_featured: false, is_active: true, sort_order: 12, created_at: daysAgo(11), updated_at: daysAgo(11), category: cat('cat-6') },
]

/** Returns true when Supabase is not yet configured */
export function isSupabaseMockMode(): boolean {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? ''
  return !url || url.includes('your_supabase') || !url.startsWith('https://')
}
